server.port=8080
provider.host=localhost
provider.rpc-path=/rpc
service-registry.connect-string=localhost:2181
service-registry.base-path=/services
service-registry.service-name=currency-rate-provider
