spring.application.name=${SPRING_APPLICATION_NAME:currency-rate-provider}
spring.profiles.default=dev
server.port=${SERVER_PORT:8080}
provider.host=${PROVIDER_HOST:localhost}
provider.rpc-path=${PROVIDER_RPC_PATH:/rpc}
service-registry.connect-string=${SERVICE_REGISTRY_CONNECT_STRING:localhost:2181}
service-registry.base-path=${SERVICE_REGISTRY_BASE_PATH:/services}
service-registry.service-name=${SERVICE_REGISTRY_NAME:currency-rate-provider}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.rpc.server.requests=true

info.app.name=${spring.application.name}
info.app.environment=${app.runtime.environment:unknown}
