spring.application.name=${SPRING_APPLICATION_NAME:rate-printer}
server.port=${SERVER_PORT:8081}
service-registry.connect-string=${SERVICE_REGISTRY_CONNECT_STRING:localhost:2181}
service-registry.base-path=${SERVICE_REGISTRY_BASE_PATH:/services}
service-registry.service-name=${SERVICE_REGISTRY_NAME:currency-rate-provider}
rate-printer.client-name=${RATE_PRINTER_CLIENT_NAME:${spring.application.name}}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

info.app.name=${spring.application.name}
